FROM nginx:1.18.0
#Stable version

# Install packages
RUN apt-get update && apt-get -y install \
	nginx-extras

#====SSL CERTIFICATE FOR NGINX====


COPY docker/nginx_load_balancer/nginx/ssl/dev.full.pem /etc/nginx/ssl/cis4250-03.socs.uoguelph.ca/full.pem
COPY docker/nginx_load_balancer/nginx/ssl/dev.key.pem /etc/nginx/ssl/cis4250-03.socs.uoguelph.ca/key.pem

# Originally generated via command: openssl dhparam -out docker/nginx_load_balancer/nginx/dhparam.pem 4096
COPY docker/nginx_load_balancer/nginx/dhparam.pem /etc/nginx/dhparam.pem

#====NGINX====
RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx_load_balancer/nginx/snippets/ssl.conf /etc/nginx/snippets/ssl.conf
COPY docker/nginx_load_balancer/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx_load_balancer/nginx/cis4250-03.socs.uoguelph.ca.dev.conf /etc/nginx/conf.d/cis4250-03.socs.uoguelph.ca.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
